### ISSUE TITLE
Instalation error using ZPM

### ISSUE THREAD

**Issue by jtsalten** [SergeyMi37/apptools-admin#2]
Hi,
trying to install it with ZPM in an IRIS 2020.1.0.215, locale espw.

The installation starts and seems to be fine till end:

MQTT>zpm
zpm: MQTT>install apptools-admin
 
[apptools-admin]        Reload START
[apptools-admin]        Reload SUCCESS
[apptools-admin]        Module object refreshed.
[apptools-admin]        Validate START
[apptools-admin]        Validate SUCCESS
[apptools-admin]        Compile START
[apptools-admin]        Compile SUCCESS
[apptools-admin]        Activate START
[apptools-admin]        Configure START
[apptools-admin]        Configure FAILURE - ERROR #875: El rol coincidente : no existe.
[apptools-admin]        Activate FAILURE - ERROR #875: El rol coincidente : no existe.
ERROR #875: El rol coincidente : no existe.
zpm: MQTT>exit
 
MQTT>w $zv
IRIS for Windows (x86-64) 2020.1 (Build 215U) Mon Mar 30 2020 20:14:33 EDT
MQTT>

**Comment by SergeyMi37** [comment]
This error is due to the fact that your system does not have a database role, in this case %DB_MQTT

**Comment by SergeyMi37** [comment]
I parsed this error in the issue
https://github.com/intersystems-community/zpm/issues/149
In version ZPM 0.2.6 the message will be clearer.
