### ISSUE TITLE
Docker-compose version issue

### ISSUE THREAD

**Issue by ghost** [SergeyMi37/apptools-admin#4]
When running docker-compose up

ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

**Comment by SergeyMi37** [comment]
Fixed in version 3.6
Thank you
