### ISSUE TITLE
IPM installation failed 

### ISSUE THREAD

**Issue by Frisle** [SergeyMi37/apptools-admin#5]
With an error 

`ERROR! Error compiling routine: apptools.core.ContextSearch.  Errors:  apptools.core.ContextSearch.cls
ERROR:  apptools.core.ContextSearch.1(7) : MPP5635 : No include file 'Ensemble'
 TEXT: #include Ensemble`

**Comment by SergeyMi37** [comment]
Fixed.

**Comment by SergeyMi37** [comment]
Thx.
